- hosts: ansible_provisioners
  become: yes
  #remote_user: root
  gather_facts: yes
  tasks:
  - name: find disk space available.
    command: vault kv get secretsv2/crypto/peerOrganizations/carrier-net/peers/peer0.carrier-net/msp/ 
    register: result 
  - name: Print-Value
    debug:
      var: result.stdout
