apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.204.81.154:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIOIDa03CZAlKBfDK8dypxg0XSWWRkvrVBbT8YTZ0/geTEpxeCpleCpZeCngKWggBEAEaBgi5
      l5SeBiIKc3lzY2hhbm5lbCpANDc1NGNlZjI4NjYwYTBjMDM2MjEyZDUwYjg4YWJiMGFlNTM1NTRl
      NzUzMjI5NjhhNWI2MmQzNjZjMzkwMGU2MxIaEhgvj4QcqHi2c6ByOhYBcWGnQswFKIJGtGISmV0K
      ll0Sk10SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVSk9UWmNDRWNVTlNkQVdSK2d1bWNUdXBlQ29rd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EWTFNVEU1V2hjTk1qVXhNVEExTURZMU1URTVX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMcDla
      amtYYXJFckd3TEdTekZ3UXFKK3gyTXhldWdRaEtnN0sxaTNnT0c1WG94UVBTWm4KZUE1Ym5JZWtq
      OTFadThlbFZtVUVoRW90Yi9mOGpXK3ZEWUtqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXF6a2N3SDdBbkZpS2ora1dZbjNLc21Q
      MmZlVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBZy8xckVudVMyL3BDU3k5SUVXMjkvcGdrWG8r
      RzZpOHBFZjZEK3lQTXoKWGdJZ1RWV3VTckVyb3lEcitUSzBZWUZ5RXIzMWt1Y1EyZnhHSU56Mnpt
      eU9QZGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVT2xMaTdzSFZCaFBtQWV4RGlqMFBmMFFPUHdNd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EWTFOakF3V2hjTk1q
      UXdNVEUyTURjd01UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFd29tT1hSS3k0aFhGbk9pYUtHbGtGU3NObDJ1
      aWo1cjkKVkpCYzJROHJFNE45ajNTTUxKRjFBbjg3VTJIVVFnSGVmTlZPbnR6MWlDRitFT2hkcXA2
      TXZhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTOFM1a1RRRXJhCjZRRDBOWmtqQ1B4UWtDb25vREFmQmdOVkhTTUVHREFXZ0JR
      cXprY3dIN0FuRmlLaitrV1luM0tzbVAyZmVUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05XSmpZMkkyTjJSakxYSm5ZbXRvTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnYnJmRXV4U3M1TnhkY0xucnkyY2JlZDZpbVFoOXlPaGhOUmdXTVZvQzBxQUNJRFZR
      QmU4YS9Jb2RvMUhJClhwYkVMMHh3UDlua0ZVWlVZMDhqRGdiVTk1Wk4KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVSk9UWmNDRWNVTlNkQVdSK2d1bWNUdXBlQ29rd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EWTFNVEU1V2hjTk1qVXhNVEEx
      TURZMU1URTVXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJMcDlaamtYYXJFckd3TEdTekZ3UXFKK3gyTXhldWdRaEtnN0sxaTNnT0c1WG94UVBTWm4K
      ZUE1Ym5JZWtqOTFadThlbFZtVUVoRW90Yi9mOGpXK3ZEWUtqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXF6a2N3SDdBbkZpS2or
      a1dZbjNLc21QMmZlVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBZy8xckVudVMyL3BDU3k5SUVX
      MjkvcGdrWG8rRzZpOHBFZjZEK3lQTXoKWGdJZ1RWV3VTckVyb3lEcitUSzBZWUZ5RXIzMWt1Y1Ey
      ZnhHSU56MnpteU9QZGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooS
      Cg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJB
      Z0lVRnducStUbjlVR29KNFJ6ZXI4ci9RL0R0TWc0d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nak13TVRFMk1EWTFOakF3V2hjTk1qUXdNVEUyTURjd01UQXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBVFM4Ynpwd1pLNHlsUXJNQ3hpbExTS3YxK0YKRzdEWkhJU3pab0F6bE9kQnpz
      Qm9uWjZ5NTBLSE9rdlZnRlMzVmY5TVE1TDQrYVhkZU5NWnNzajhiZXI5bzRJQgpNakNDQVM0d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUk9vc2g5Q2g3QmE0VENEbVZiVk44
      bVRoMlkKVlRBZkJnTlZIU01FR0RBV2dCUXF6a2N3SDdBbkZpS2ora1dZbjNLc21QMmZlVEJCQmdO
      VkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJ
      eExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25N
      aU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lK
      dmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhK
      bGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFwd2JoZ29NVGRmbGxOCmErdG5nemsyelBS
      UUxFbFhHUk54TUU0MENDQk01QUlnR29GUTRkNWVsNWlDMU55Njd6cWNFVitUM0lzUEdBTDYKSktY
      RW55YllyMUE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJBZ0lVRnducStUbjlVR29KNFJ6ZXI4ci9RL0R0TWc0
      d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZ
      RFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EWTFOakF3V2hj
      Tk1qUXdNVEUyTURjd01UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRF
      dU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFR
      TEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVFM4Ynpwd1pLNHlsUXJNQ3hp
      bExTS3YxK0YKRzdEWkhJU3pab0F6bE9kQnpzQm9uWjZ5NTBLSE9rdlZnRlMzVmY5TVE1TDQrYVhk
      ZU5NWnNzajhiZXI5bzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFX
      TUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVk
      RGdRV0JCUk9vc2g5Q2g3QmE0VENEbVZiVk44bVRoMlkKVlRBZkJnTlZIU01FR0RBV2dCUXF6a2N3
      SDdBbkZpS2ora1dZbjNLc21QMmZlVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3
      YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkK
      TENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVa
      WFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVB
      aUFwd2JoZ29NVGRmbGxOCmErdG5nemsyelBSUUxFbFhHUk54TUU0MENDQk01QUlnR29GUTRkNWVs
      NWlDMU55Njd6cWNFVitUM0lzUEdBTDYKSktYRW55YllyMUE9Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICA
      MRiAgEAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9j
      a1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1p
      bnMSty8KC0NvbnNvcnRpdW1zEqcvEtwuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Swi4StxcKD21h
      bnVmYWN0dXJlck1TUBKjFxqrFQoDTVNQEqMVEpgVEpUVCg9tYW51ZmFjdHVyZXJNU1AShgYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVEYTRhT1RpN2k1M1NE
      MXZ4U3lsQ1NYMktYbk13Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpNd01URTJNRFkxTWpNeFdoY05NalV4TVRBMU1EWTFNak14V2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJN1gvY1dxRWE3QUk5
      STRBVy9pWDg1SDdCVDdlT2EwektKSwphY0oraHRjbzQ5YmlScTdxbitSWUdNZ0VmZ213TEN0RVJm
      SXdCck4yZGU0NDZIQUp0bEtqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUlF3RllZV2g4ZHJGN04KY3BpbmRGZzdvYzNtQXpBS0Jn
      Z3Foa2pPUFFRREFnTkpBREJHQWlFQXdMd1UxalQrTXBxaDBmNG4zcjdjTEZmdwp5Q2l2alFPUFV2
      R3hmUEZiNHpnQ0lRRHVIRkxoSzJ3d0dWVjBqQ0xsbFF5NW0rY2NhUmhUOU9lNFU0YXI4QnpJCmN3
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi3wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJRERqQ0NBcldnQXdJQkFnSVVGOUlzNEZOK0Z2ZUFNMjJmZTIrWXZOaUt5Vk13Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd01URTJNRFkxT0RBd1do
      Y05NalF3TVRFMk1EY3dNekF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVU
      UTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6
      QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZR
      UUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SQp6ajBEQVFjRFFnQUV4QTlUOU1TeHkwOHpmTU9UMURvdzJ2V1dSUUgvb1JCVUY4MjhGcWp0OXR4
      OFk0MWhsbHlTCmpyOGlyR3BaRkl6ZndkMWV2VzZyZHJXS0tFVElqYTFjamFPQ0FTQXdnZ0VjTUE0
      R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFVVXJm
      ZFVHZTJwWi8vOS9GTWgwS3JFSmxqeERBZgpCZ05WSFNNRUdEQVdnQlJRd0ZZWVdoOGRyRjdOY3Bp
      bmRGZzdvYzNtQXpBaUJnTlZIUkVFR3pBWmdoZGpZUzEwCmIyOXNjeTFtTnpkalpqYzBPQzFyT0dO
      bVlqQ0Jsd1lJS2dNRUJRWUhDQUVFZ1lwN0ltRjBkSEp6SWpwN0ltRmkKWVdNdWFXNXBkQ0k2SW5S
      eWRXVWlMQ0poWkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNgpJbTFoYm5W
      bVlXTjBkWEpsY2lJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUcxaGJuVm1ZV04w
      CmRYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBd1JBSWcKR0Qyb0lFVnpLZ09kc29sbXo2UnlUNXhjRHNiNnhvU0FVQzF6RWdaWFR2QUNJRTVJ
      MGdmRkxnVXExQ2JBUmRCbQpKeHQ4MGFmWFRiTDhON3dDRzU2SDNOQi8KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNEVENDQWJLZ0F3SUJBZ0lVRGE0YU9UaTdpNTNTRDF2eFN5bENTWDJLWG5Nd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdNVEUyTURZMU1qTXhXaGNO
      TWpVeE1UQTFNRFkxTWpNeFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5
      YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEps
      Y2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5
      QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSTdYL2NXcUVhN0FJOUk0QVcvaVg4NUg3QlQ3ZU9hMHpLSksK
      YWNKK2h0Y280OWJpUnE3cW4rUllHTWdFZmdtd0xDdEVSZkl3QnJOMmRlNDQ2SEFKdGxLalFqQkFN
      QThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdC
      QlJRd0ZZWVdoOGRyRjdOCmNwaW5kRmc3b2MzbUF6QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUF3
      THdVMWpUK01wcWgwZjRuM3I3Y0xGZncKeUNpdmpRT1BVdkd4ZlBGYjR6Z0NJUUR1SEZMaEsyd3dH
      VlYwakNMbGxReTVtK2NjYVJoVDlPZTRVNGFyOEJ6SQpjdz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFj
      dHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFj
      dHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKqFgoKY2Fycmllck1TUBKbFhq3FAoDTVNQ
      Eq8UEqQUEqEUCgpjYXJyaWVyTVNQEuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5
      ekNDQVo2Z0F3SUJBZ0lVUDVPWFNzOE81NnhDZzg1QlE4SVkzVld6WTU0d0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck16QXhNVFl3TmpVek5ETmFGdzB5TlRFeE1EVXdOalV6TkROYU1G
      b3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJr
      eHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNt
      bGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUjhnMmVrWTRSMUd6
      ditmcjVUUW1Sd2RRM3FYc1YyY3JmNE5zeTU0cmx5Qm53dVlnWThYbWlwRTBjUWxCVHUKR0MvZFVV
      ZkNHT2ZEMGJzZWRMdUJvaW0rbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdF
      Qgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVPQ3dtdW85VFdOYkV3K250Wkt1NmpCQ3YxcVF3Q2dZ
      SUtvWkl6ajBFCkF3SURSd0F3UkFJZ1dEZUgyV09MY3ZQMFBvRWRjOHRpeW9KZnJGcURlZlRIcmU4
      MkRmdG5wWUVDSUdiOE56ZlQKS05xNEt4UElSeGM5K3hQME54UkNWY2RrM1c2Nm0zMU5GZDlJCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUM3VENDQXBTZ0F3SUJBZ0lVY2ZCMkRlTDlNNDVOV1FVRFN4UHB2ZllFYTZVd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck16QXhNVFl3TmpVNU1EQmFGdzB5TkRBeE1UWXdOekEwTURC
      YU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1
      a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFV
      RUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVF2NlY5Y01rY3dhRWJnM3BTV0tJb08KUFk5
      dlhMRlR4RVpGNG8vNWtGQW9zenhqNVo0bnhVVkh3NEx3SW9Xb2pLU2FZRWN3eisrMmJKWUozK25Y
      aWpiNgpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3
      SFFZRFZSME9CQllFCkZLdGYxWTBseWlSZ1h6S1pmdTVBNDVUK05WcGJNQjhHQTFVZEl3UVlNQmFB
      RkRnc0pycVBVMWpXeE1QcDdXU3IKdW93UXI5YWtNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6
      TFRVMVptWmpPVFprTkRZdGVHZHJObTR3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2
      ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1pt
      YVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0
      YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJ
      emowRUF3SURSd0F3UkFJZ0t6ODV1U08waGczQTd4emJYWTlsaS95UERJNUx6MEVDRUIxSDlORmUz
      YXdDCklCYkpFbmRvdFNiekgzbjVtRzhIbDB5NjJRb0kwOUpCTnlyQnUxU0s2dFM3Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVVA1T1hTczhPNTZ4Q2c4NUJROElZM1ZXelk1NHdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekF4TVRZd05qVXpORE5hRncweU5URXhN
      RFV3TmpVek5ETmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVB
      d3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpB
      QVI4ZzJla1k0UjFHenYrZnI1VFFtUndkUTNxWHNWMmNyZjROc3k1NHJseUJud3VZZ1k4WG1pcEUw
      Y1FsQlR1CkdDL2RVVWZDR09mRDBic2VkTHVCb2ltK28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFR
      SC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVT0N3bXVvOVRXTmJFdytudFpL
      dTZqQkN2MXFRd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdXRGVIMldPTGN2UDBQb0VkYzh0aXlv
      SmZyRnFEZWZUSHJlODJEZnRucFlFQ0lHYjhOemZUCktOcTRLeFBJUnhjOSt4UDBOeFJDVmNkazNX
      NjZtMzFORmQ5SQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMKB1dyaXRlcnMS
      KBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgB
      EhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIe
      CAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIa
      EggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVh
      dGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhIS
      CAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8a
      BkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0
      OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFf
      NF8zEgAaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMa
      BkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
