apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.214.139.200:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaINbnZQSkpPhyf7qxk+mJ+Et6KwI1rCdcIdzfA8dqzg90EqpeCqdeCqReCngKWggBEAEaBgjt
      jJWdBiIKc3lzY2hhbm5lbCpANWU1YjkyNjJmYTg2ZDA0NjU3YmY1Mjg2YmYxZDI2NDM1ODEwZTkx
      OWNiNzgxOWQ0Zjk5ZmMzODFiODAwMWE4OBIaEhix6w6rQtq3UxPyTe8dp7WQe00EsuhqMWcSp10K
      pF0SoV0SmysKB09yZGVyZXISjysS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVV1k1ZlYyNUZpd2hpZkMvQ09iUDJ1eHdYd09rd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJek1EVTFOVFUwV2hjTk1qVXhNREV5TURVMU5UVTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQUHdE
      SXZvM01HNzNYNHMzYlA1WWlrZ2ZtUVNOTHoyWi9TOUw2SjVOTlZucFB0U0VTRlcKYmlucStxeHBD
      QVBXL3NJWkViaC9aVEZZTmo4NFlwc1VjRjJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVlQeUd0RTExWXlqeUlkaXNOaHlkTEJL
      MkRWVEFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWhhdU9aQ3dyREFBWklZa2JyT3hLREdpckR2
      SnNLdllYVWY2bWJCUlkKclQwQ0lRRFIxSVpaSWNjWGg5eXhOakgrUTZOUm1MVDNTbXRSc1pUZnd1
      c3VsblAvcUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVVVBN3VYSmM0MHJ5TUFCT3o0RUZOSUtyamYw
      Z3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qSXpNRFl3TWpBd1do
      Y05Nak14TWpJek1EWXdOekF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWs1akIweCtQNmNmdFY0YnhEUitVZGJS
      NTA0TE04WUFZCnNxZTFvM2JJRzVKOUd3WHMzUzh1b1k1RVBibUxFd24yUzRScmpjL3F4NUZaUVAx
      cVN1QzJncU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVHRZRGhzNU5XdQpsNVNITmJGUHI5bDVGb0l0OURBZkJnTlZIU01FR0RB
      V2dCUVlQeUd0RTExWXlqeUlkaXNOaHlkTEJLMkRWVEFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDJZamswT1RrNFkyWm1MWE0xYURSbU1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ0JqaUpiT28zNng5UmtYRWl1L0pOdmxCYlJPbjF5MlhzRjJZaGtTOUs5cFlD
      SUh5N1hYbm9JQVJkOWFNZgpyZThSVmVpTXNkaUM4c21uTUYvYmw0U1gvOVV4Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVVdZNWZWMjVGaXdoaWZDL0NPYlAydXh3WHdPa3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qSXpNRFUxTlRVMFdoY05NalV4
      TURFeU1EVTFOVFUwV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCUFB3REl2bzNNRzczWDRzM2JQNVlpa2dmbVFTTkx6MlovUzlMNko1Tk5WbnBQdFNF
      U0ZXCmJpbnErcXhwQ0FQVy9zSVpFYmgvWlRGWU5qODRZcHNVY0YyalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFZUHlHdEUxMVl5
      anlJZGlzTmh5ZExCSzJEVlRBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFoYXVPWkN3ckRBQVpJ
      WWtick94S0RHaXJEdkpzS3ZZWFVmNm1iQlJZCnJUMENJUURSMUlaWkljY1hoOXl4TmpIK1E2TlJt
      TFQzU210UnNaVGZ3dXN1bG5QL3FBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zIjcKB1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0
      Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlu
      cxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaihIKDUNvbnNlbnN1c1R5
      cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca0wgt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREJUQ0NBcXVnQXdJQkFnSVVHWVBkK09rVEtw
      VVRsMjJ4a0c3R0lKZ0ZFRFV3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6
      QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RB
      ZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1q
      SXhNakl6TURZd01qQXdXaGNOTWpNeE1qSXpNRFl3TnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpF
      YgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21S
      bGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFT
      TjUvTXh3N0FnMUgrUE1VazhYM2tLRnBFYgoxeGFOOWQzV3dLczB4b3diTkk3aHliYThEaTRiemRM
      aU1SSEFYU1JabVl0LzgxWEh2UG81d2ViZ3F4UXhvNElCCk1qQ0NBUzR3RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUc0NoWkZicEx4ZUVRcG5EMkJPZDl1WWFLWAoyVEFmQmdO
      VkhTTUVHREFXZ0JRWVB5R3RFMTFZeWp5SWRpc05oeWRMQksyRFZUQkJCZ05WSFJFRU9qQTRnaGh2
      CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDSEc5eVpHVnlaWEl4TG5Wd1ozSmhaR1V1
      ZFhCbmNtRmsKWlM1amIyMHdiQVlJS2dNRUJRWUhDQUVFWUhzaVlYUjBjbk1pT25zaWFHWXVRV1pt
      YVd4cFlYUnBiMjRpT2lJaQpMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUp2Y21SbGNtVnlNUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYUWlMQ0pvClppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOWZUQUtCZ2dx
      aGtqT1BRUURBZ05JQURCRkFpRUFzWTRDWXQ1cnlHeFQKOWppQ0JpcDlyWXVUNmlMb0dSWnFWWEw2
      VGpaQkU2SUNJRWJnd2JvWXJsVzFiRTcxRnN0WXRNK1JOTFlnWGxLaApvbGszaTBWRTMwY24KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      REJUQ0NBcXVnQXdJQkFnSVVHWVBkK09rVEtwVVRsMjJ4a0c3R0lKZ0ZFRFV3Q2dZSUtvWkl6ajBF
      QXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNakl6TURZd01qQXdXaGNOTWpNeE1qSXpNRFl3
      TnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12
      VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5
      TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTTjUvTXh3N0FnMUgrUE1VazhYM2tLRnBFYgoxeGFO
      OWQzV3dLczB4b3diTkk3aHliYThEaTRiemRMaU1SSEFYU1JabVl0LzgxWEh2UG81d2ViZ3F4UXhv
      NElCCk1qQ0NBUzR3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZC
      d01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUc0NoWkZi
      cEx4ZUVRcG5EMkJPZDl1WWFLWAoyVEFmQmdOVkhTTUVHREFXZ0JRWVB5R3RFMTFZeWp5SWRpc05o
      eWRMQksyRFZUQkJCZ05WSFJFRU9qQTRnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVa
      WFNDSEc5eVpHVnlaWEl4TG5Wd1ozSmhaR1V1ZFhCbmNtRmsKWlM1amIyMHdiQVlJS2dNRUJRWUhD
      QUVFWUhzaVlYUjBjbk1pT25zaWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lJaQpMQ0pvWmk1RmJuSnZi
      R3h0Wlc1MFNVUWlPaUp2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUWlMQ0pvClppNVVl
      WEJsSWpvaWIzSmtaWEpsY2lKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFzWTRDWXQ1cnlH
      eFQKOWppQ0JpcDlyWXVUNmlMb0dSWnFWWEw2VGpaQkU2SUNJRWJnd2JvWXJsVzFiRTcxRnN0WXRN
      K1JOTFlnWGxLaApvbGszaTBWRTMwY24KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAw
      bXMQChgBIAUogICAChoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1p
      bnMqBkFkbWlucxK9LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLI
      LhK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsUErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lVSitCOFJrZDVZQmtDWnhi
      RGVUMEVnK0VpZ2g0d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhK
      eWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNak13TlRV
      NE1qZGFGdzB5TlRFd01USXdOVFU0TWpkYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxs
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBUTU5TWVRYzlRZHp1aExMVEc5eXVJSXNINExmRTZkZGxxeERsdkk3b0RQ
      TVBxQmlGekFSK3FBc2RrRmdPU2wKYVlOOWdwRk9UUnczMStrSEdBS0IyWDFlbzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVUvTk4z
      QkcvTnIzVHp5bVhkUkVzQi84MW12eEV3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFKUzdEOWs3
      NEx5YTVJeHg2aXlteEZGQk9QUmE0VFVqZUkwWWRaZUVzbytqQWlFQTZheGIKVHovVFFEc2tvYnh1
      czRRZVV6bmI2bkY2Q3FoMXVHMEtPd2F1bGV3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2
      CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN2pDQ0FwU2dBd0lCQWdJVWJMeFpoa05J
      Z0tSc0RDNGdIa2RhVko5T1ZVNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFL
      REFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5
      TWpNd05qQTFNREJhRncweU16RXlNak13TmpFd01EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dH
      UVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBa
      WEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVB
      d3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DQUFUNFlYcTJDVTZDQzFCcVFlNlkvY2pBCnZoaUFzajcxZXVqb1ByOEVEaDhRME1jR1VvWGMw
      dkdaZlcxQnlIdVNvb1ZRV0ZFTENpakxyeW9DTWhVcGloTFIKbzRJQkdEQ0NBUlF3RGdZRFZSMFBB
      UUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpGR2pVc3lWNjI5KzMx
      QUF2cnludjJBb0JHNjB1TUI4R0ExVWRJd1FZTUJhQUZQelRkd1J2emE5MDg4cGwzVVJMCkFmL05a
      cjhSTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUVmtabVJqTkRsa05EZ3RkRGxzYmpVd2dZ
      MEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElp
      d2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlp
      d2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1pp
      NVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEU0FBd1JRSWhBTU43OFRocGNF
      ZEwzbWF4djBJdUp4ZDU3T0FCbUg0Rk1qUkU5NGk5SjNzRApBaUFhMFJZRE1rcEE4VFUrdlJjdU16
      aXlKM3ZadThVakthQkhiaFMydy9SR3dnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoE
      U0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3
      SUJBZ0lVSitCOFJrZDVZQmtDWnhiRGVUMEVnK0VpZ2g0d0NnWUlLb1pJemowRUF3SXcKV2pFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1
      bGREQWVGdzB5Ck1qRXlNak13TlRVNE1qZGFGdzB5TlRFd01USXdOVFU0TWpkYU1Gb3hDekFKQmdO
      VkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpF
      UU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUTU5TWVRYzlRZHp1aExMVEc5eXVJ
      SXNINExmRTZkZGxxeERsdkk3b0RQTVBxQmlGekFSK3FBc2RrRmdPU2wKYVlOOWdwRk9UUnczMStr
      SEdBS0IyWDFlbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJ
      QnBqQWRCZ05WSFE0RUZnUVUvTk4zQkcvTnIzVHp5bVhkUkVzQi84MW12eEV3Q2dZSUtvWkl6ajBF
      CkF3SURTUUF3UmdJaEFKUzdEOWs3NEx5YTVJeHg2aXlteEZGQk9QUmE0VFVqZUkwWWRaZUVzbytq
      QWlFQTZheGIKVHovVFFEc2tvYnh1czRRZVV6bmI2bkY2Q3FoMXVHMEtPd2F1bGV3PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwK
      CmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJy
      aWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNh
      cnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zErEXCg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKd
      FRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUNERENDQWJLZ0F3SUJBZ0lVQjBGUGRBSjB2RndvRndoRzd4RWNQa1c5T2c0d0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakl6TURVMU56QTVXaGNOTWpV
      eE1ERXlNRFUxTnpBNVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdO
      b01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pF
      Y01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdF
      R0NDcUdTTTQ5QXdFSEEwSUFCSkxOS2w2Uk5sMUpYT3A2YVlhWlhRVjFjZTFXcDJwSEpsejkKWXFE
      Y0ZiOEhkSWU5YmNiekJFMnFxcmJtd0piVG9IYTNpOHEzaHFyVnNvbnlUaTF0V0NLalFqQkFNQThH
      QTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlIr
      b0NwNW5JWFIxSWpsCnRYeUFBYXNuNndkTjJUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQk9xczNE
      RnJYSE9XNkQ4WklJc0tDZWlOYmYKVHRKK2tOYk9kRmhrWTNYRzRBSWhBS3BsY2lGaTJGTHN1ZHJ2
      M1hHeHhKT1V1VkUzakYxcDZOekRIdStwUlFCTAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLj
      CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERURDQ0FyZWdBd0lCQWdJVUxqeGc5VXd3
      aW16YXRiaE15QzFMRGUvei9HRXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4
      RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFL
      REF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1
      WlhRd0hoY05Nakl4TWpJek1EWXdNekF3V2hjTk1qTXhNakl6TURZd09EQXdXakNCaGpFTE1Ba0dB
      MVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURW
      UVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1i
      V0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRi
      bVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdBRWpsZmp6RWpBNG1GRzVnWXVF
      MmRQUERmRGtkQWthZ05MVm1IY1JCSUtielZBZVlnMUV3bjMKdWdjY05MMFUxMkFkNENTUS9JOWs1
      U0tZUjJuUWM5VzljS09DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJB
      ZjhFQWpBQU1CMEdBMVVkRGdRV0JCVDZrb2RXbmJQOXVVcmFrUzlEbkIwSDJpWGowakFmCkJnTlZI
      U01FR0RBV2dCUitvQ3A1bklYUjFJamx0WHlBQWFzbjZ3ZE4yVEFrQmdOVkhSRUVIVEFiZ2hsallT
      MTAKYjI5c2N5MDRObUprT1RSak9UWTJMV0pzYm14a01JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlY
      UjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0lt
      aG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JX
      VnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9p
      SmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRQpBaUFtZWdxR3hsNHZjSE1hZW1wWnBB
      RUlkdDZKcHArMnMrNjR5QkJRRWFJYUh3SWdTMmdsNmc3Q0J6RXlqUG9ICm9YVWgvODVXV2UwbWN2
      aENvTngreXFodWJCST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2
      SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVQjBGUGRB
      SjB2RndvRndoRzd4RWNQa1c5T2c0d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1Ew
      Z3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZR
      UUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNp
      MXVaWFF3SGhjTk1qSXhNakl6TURVMU56QTVXaGNOTWpVeE1ERXlNRFUxTnpBNVdqQmtNUXN3Q1FZ
      RFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJn
      eEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFda
      aFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSkxOS2w2
      Uk5sMUpYT3A2YVlhWlhRVjFjZTFXcDJwSEpsejkKWXFEY0ZiOEhkSWU5YmNiekJFMnFxcmJtd0pi
      VG9IYTNpOHEzaHFyVnNvbnlUaTF0V0NLalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZ
      RFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlIrb0NwNW5JWFIxSWpsCnRYeUFBYXNuNndk
      TjJUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQk9xczNERnJYSE9XNkQ4WklJc0tDZWlOYmYKVHRK
      K2tOYk9kRmhrWTNYRzRBSWhBS3BsY2lGaTJGTHN1ZHJ2M1hHeHhKT1V1VkUzakYxcDZOekRIdStw
      UlFCTAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAES
      HxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAES
      IRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50
      Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVy
      cxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMa
      QAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hp
      bmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0
      dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0
      aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
