apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.214.139.200:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaICGH97jFIIs7XY/VIsiLMT976B/HeT1UPHyt0JLie97NEqpeCqdeCqReCngKWggBEAEaBgje
      npWdBiIKc3lzY2hhbm5lbCpANTgxNGM4ZGM1ZjAxOGI2ZjNhYThkNTMwZTFjM2JhMWY4ODc5ZTIw
      ZDY5YTk4MjY1NWU1ZjM3ZDQ0MDU4N2U4NhIaEhjTDdJ6swiFZwio7WtnPnCjQ3rrjpr1CLkSp10K
      pF0SoV0SmysKB09yZGVyZXISjysS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVV1k1ZlYyNUZpd2hpZkMvQ09iUDJ1eHdYd09rd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJek1EVTFOVFUwV2hjTk1qVXhNREV5TURVMU5UVTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQUHdE
      SXZvM01HNzNYNHMzYlA1WWlrZ2ZtUVNOTHoyWi9TOUw2SjVOTlZucFB0U0VTRlcKYmlucStxeHBD
      QVBXL3NJWkViaC9aVEZZTmo4NFlwc1VjRjJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVlQeUd0RTExWXlqeUlkaXNOaHlkTEJL
      MkRWVEFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWhhdU9aQ3dyREFBWklZa2JyT3hLREdpckR2
      SnNLdllYVWY2bWJCUlkKclQwQ0lRRFIxSVpaSWNjWGg5eXhOakgrUTZOUm1MVDNTbXRSc1pUZnd1
      c3VsblAvcUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVVVBN3VYSmM0MHJ5TUFCT3o0RUZOSUtyamYw
      Z3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qSXpNRFl3TWpBd1do
      Y05Nak14TWpJek1EWXdOekF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWs1akIweCtQNmNmdFY0YnhEUitVZGJS
      NTA0TE04WUFZCnNxZTFvM2JJRzVKOUd3WHMzUzh1b1k1RVBibUxFd24yUzRScmpjL3F4NUZaUVAx
      cVN1QzJncU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVHRZRGhzNU5XdQpsNVNITmJGUHI5bDVGb0l0OURBZkJnTlZIU01FR0RB
      V2dCUVlQeUd0RTExWXlqeUlkaXNOaHlkTEJLMkRWVEFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDJZamswT1RrNFkyWm1MWE0xYURSbU1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ0JqaUpiT28zNng5UmtYRWl1L0pOdmxCYlJPbjF5MlhzRjJZaGtTOUs5cFlD
      SUh5N1hYbm9JQVJkOWFNZgpyZThSVmVpTXNkaUM4c21uTUYvYmw0U1gvOVV4Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVVdZNWZWMjVGaXdoaWZDL0NPYlAydXh3WHdPa3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qSXpNRFUxTlRVMFdoY05NalV4
      TURFeU1EVTFOVFUwV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCUFB3REl2bzNNRzczWDRzM2JQNVlpa2dmbVFTTkx6MlovUzlMNko1Tk5WbnBQdFNF
      U0ZXCmJpbnErcXhwQ0FQVy9zSVpFYmgvWlRGWU5qODRZcHNVY0YyalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFZUHlHdEUxMVl5
      anlJZGlzTmh5ZExCSzJEVlRBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFoYXVPWkN3ckRBQVpJ
      WWtick94S0RHaXJEdkpzS3ZZWFVmNm1iQlJZCnJUMENJUURSMUlaWkljY1hoOXl4TmpIK1E2TlJt
      TFQzU210UnNaVGZ3dXN1bG5QL3FBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJp
      bGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0RCghl
      dGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1Z0F3SUJBZ0lVR1lQZCtPa1RLcFVUbDIyeGtHN0dJ
      SmdGRURVd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJek1EWXdN
      akF3V2hjTk1qTXhNakl6TURZd056QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVC
      eE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpE
      Z1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU041L014dzdBZzFI
      K1BNVWs4WDNrS0ZwRWIKMXhhTjlkM1d3S3MweG93Yk5JN2h5YmE4RGk0YnpkTGlNUkhBWFNSWm1Z
      dC84MVhIdlBvNXdlYmdxeFF4bzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0Ex
      VWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1C
      MEdBMVVkRGdRV0JCVHNDaFpGYnBMeGVFUXBuRDJCT2Q5dVlhS1gKMlRBZkJnTlZIU01FR0RBV2dC
      UVlQeUd0RTExWXlqeUlkaXNOaHlkTEJLMkRWVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1T
      NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpT
      NWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0
      aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdG
      cGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdO
      SUFEQkZBaUVBc1k0Q1l0NXJ5R3hUCjlqaUNCaXA5cll1VDZpTG9HUlpxVlhMNlRqWkJFNklDSUVi
      Z3dib1lybFcxYkU3MUZzdFl0TStSTkxZZ1hsS2gKb2xrM2kwVkUzMGNuCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1Z0F3
      SUJBZ0lVR1lQZCtPa1RLcFVUbDIyeGtHN0dJSmdGRURVd0NnWUlLb1pJemowRUF3SXcKWGpFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdG
      cGJpMXVaWFF3CkhoY05Nakl4TWpJek1EWXdNakF3V2hjTk1qTXhNakl6TURZd056QXdXakJ4TVFz
      d0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJB
      d0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFR
      REV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdn
      cWhrak9QUU1CQndOQ0FBU041L014dzdBZzFIK1BNVWs4WDNrS0ZwRWIKMXhhTjlkM1d3S3MweG93
      Yk5JN2h5YmE4RGk0YnpkTGlNUkhBWFNSWm1ZdC84MVhIdlBvNXdlYmdxeFF4bzRJQgpNakNDQVM0
      d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VG
      CkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVHNDaFpGYnBMeGVFUXBuRDJC
      T2Q5dVlhS1gKMlRBZkJnTlZIU01FR0RBV2dCUVlQeUd0RTExWXlqeUlkaXNOaHlkTEJLMkRWVEJC
      QmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5
      WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIw
      Y25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFp
      T2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0pr
      WlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBc1k0Q1l0NXJ5R3hUCjlqaUNCaXA5
      cll1VDZpTG9HUlpxVlhMNlRqWkJFNklDSUViZ3dib1lybFcxYkU3MUZzdFl0TStSTkxZZ1hsS2gK
      b2xrM2kwVkUzMGNuCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICA
      gAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5z
      IiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZB
      ZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMqBkFkbWlucxK9LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLI
      LhKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1T
      UBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUIwRlBk
      QUowdkZ3b0Z3aEc3eEVjUGtXOU9nNHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURW
      UVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApj
      aTF1WlhRd0hoY05Nakl4TWpJek1EVTFOekE1V2hjTk1qVXhNREV5TURVMU56QTVXakJrTVFzd0NR
      WURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFky
      Z3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRX
      WmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkpMTkts
      NlJObDFKWE9wNmFZYVpYUVYxY2UxV3AycEhKbHo5CllxRGNGYjhIZEllOWJjYnpCRTJxcXJibXdK
      YlRvSGEzaThxM2hxclZzb255VGkxdFdDS2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0Rn
      WURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSK29DcDVuSVhSMUlqbAp0WHlBQWFzbjZ3
      ZE4yVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUJPcXMzREZyWEhPVzZEOFpJSXNLQ2VpTmJmClR0
      SitrTmJPZEZoa1kzWEc0QUloQUtwbGNpRmkyRkxzdWRydjNYR3h4Sk9VdVZFM2pGMXA2TnpESHUr
      cFJRQkwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVManhnOVV3d2ltemF0YmhNeUMxTERlL3ovR0V3Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qSXpNRFl3TXpB
      d1doY05Nak14TWpJek1EWXdPREF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJ
      eEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZ
      RFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSQp6ajBEQVFjRFFnQUVqbGZqekVqQTRtRkc1Z1l1RTJkUFBEZkRrZEFrYWdOTFZtSGNSQklL
      YnpWQWVZZzFFd24zCnVnY2NOTDBVMTJBZDRDU1EvSTlrNVNLWVIyblFjOVc5Y0tPQ0FTSXdnZ0Vl
      TUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlQ2
      a29kV25iUDl1VXJha1M5RG5CMEgyaVhqMGpBZgpCZ05WSFNNRUdEQVdnQlIrb0NwNW5JWFIxSWps
      dFh5QUFhc242d2ROMlRBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTA0Tm1Ka09UUmpPVFky
      TFdKc2JteGtNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9p
      YldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVk
      V1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkUKQWlBbWVncUd4bDR2Y0hNYWVtcFpwQUVJZHQ2SnBwKzJzKzY0eUJCUUVhSWFI
      d0lnUzJnbDZnN0NCekV5alBvSApvWFVoLzg1V1dlMG1jdmhDb054K3lxaHViQkk9Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUIwRlBkQUowdkZ3b0Z3aEc3eEVjUGtXOU9nNHdD
      Z1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGph
      REVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhI
      REFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpJek1EVTFO
      ekE1V2hjTk1qVXhNREV5TURVMU56QTVXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVD
      QXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1Z
      V04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpC
      eXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkpMTktsNlJObDFKWE9wNmFZYVpYUVYxY2UxV3Ay
      cEhKbHo5CllxRGNGYjhIZEllOWJjYnpCRTJxcXJibXdKYlRvSGEzaThxM2hxclZzb255VGkxdFdD
      S2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0Ex
      VWREZ1FXQkJSK29DcDVuSVhSMUlqbAp0WHlBQWFzbjZ3ZE4yVEFLQmdncWhrak9QUVFEQWdOSUFE
      QkZBaUJPcXMzREZyWEhPVzZEOFpJSXNLQ2VpTmJmClR0SitrTmJPZEZoa1kzWEc0QUloQUtwbGNp
      RmkyRkxzdWRydjNYR3h4Sk9VdVZFM2pGMXA2TnpESHUrcFJRQkwKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFj
      dHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEK
      D21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIR
      Cg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNN
      U1ASuxQSsBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      QitUQ0NBWjZnQXdJQkFnSVVKK0I4UmtkNVlCa0NaeGJEZVQwRWcrRWlnaDR3Q2dZSUtvWkl6ajBF
      QXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVq
      WVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1qTXdOVFU0TWpkYUZ3MHlOVEV3TVRJd05UVTRNamRh
      TUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNN
      Qmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5
      Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRNTlNZVFjOVFk
      enVoTExURzl5dUlJc0g0TGZFNmRkbHF4RGx2STdvRFBNUHFCaUZ6QVIrcUFzZGtGZ09TbAphWU45
      Z3BGT1RSdzMxK2tIR0FLQjJYMWVvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWRE
      d0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVS9OTjNCRy9OcjNUenltWGRSRXNCLzgxbXZ4RXdD
      Z1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUpTN0Q5azc0THlhNUl4eDZpeW14RkZCT1BSYTRUVWpl
      STBZZFplRXNvK2pBaUVBNmF4YgpUei9UUURza29ieHVzNFFlVXpuYjZuRjZDcWgxdUcwS093YXVs
      ZXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUM3akNDQXBTZ0F3SUJBZ0lVYkx4WmhrTklnS1JzREM0Z0hrZGFWSjlPVlU0d0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNak13TmpBMU1EQmFGdzB5TXpFeU1qTXdO
      akV3TURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhN
      eTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVN
      QTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVQ0WVhxMkNVNkNDMUJxUWU2WS9j
      akEKdmhpQXNqNzFldWpvUHI4RURoOFEwTWNHVW9YYzB2R1pmVzFCeUh1U29vVlFXRkVMQ2lqTHJ5
      b0NNaFVwaWhMUgpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93
      UUNNQUF3SFFZRFZSME9CQllFCkZHalVzeVY2MjkrMzFBQXZyeW52MkFvQkc2MHVNQjhHQTFVZEl3
      UVlNQmFBRlB6VGR3UnZ6YTkwODhwbDNVUkwKQWYvTlpyOFJNQ1FHQTFVZEVRUWRNQnVDR1dOaExY
      UnZiMnh6TFRWa1ptUmpORGxrTkRndGREbHNialV3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRI
      UnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFH
      WXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlq
      b2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZ
      SQpLb1pJemowRUF3SURTQUF3UlFJaEFNTjc4VGhwY0VkTDNtYXh2MEl1SnhkNTdPQUJtSDRGTWpS
      RTk0aTlKM3NECkFpQWEwUllETWtwQThUVSt2UmN1TXppeUozdlp1OFVqS2FCSGJoUzJ3L1JHd2c9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVKK0I4UmtkNVlCa0NaeGJEZVQw
      RWcrRWlnaDR3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1qTXdOVFU0TWpk
      YUZ3MHlOVEV3TVRJd05UVTRNamRhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFRNTlNZVFjOVFkenVoTExURzl5dUlJc0g0TGZFNmRkbHF4RGx2STdvRFBNUHFC
      aUZ6QVIrcUFzZGtGZ09TbAphWU45Z3BGT1RSdzMxK2tIR0FLQjJYMWVvMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVS9OTjNCRy9O
      cjNUenltWGRSRXNCLzgxbXZ4RXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUpTN0Q5azc0THlh
      NUl4eDZpeW14RkZCT1BSYTRUVWplSTBZZFplRXNvK2pBaUVBNmF4YgpUei9UUURza29ieHVzNFFl
      VXpuYjZuRjZDcWgxdUcwS093YXVsZXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9y
      c2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMa
      QAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hp
      bmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0
      dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0
      aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
