apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.204.81.154:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIFmU7f1AEcJb9ev3gVataVYv7JtK9Gx1BzzcpHqtbPkOEqheCqVeCqJeCngKWggBEAEaBgjg
      y5OeBiIKc3lzY2hhbm5lbCpANjNmMTM2OWIxZTU0ZGZjNWI0NTUzMDllNmY1YTdiZWY5NGZiZTA2
      ZDE2MmZmNTg4NTIyNjNmMWEzZTViZmY1YhIaEhgX25aTnAyy+XsR/UAf75kdf1/nn2ZiJJASpV0K
      ol0Sn10SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWE9nM21GbWhRVlA1KzJoSVFWb0ZnTVlreStJd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EUTFPREUwV2hjTk1qVXhNVEExTURRMU9ERTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJIdjhR
      L2NFeHhHb3laVFdNaWg0ajFsT0d3elYzUkVVWnJLODFFdmJ4TjRKQm9tUDFpeDMKQWdTZENXanVZ
      MCttOGdjTnlIUHJVaFRieGVjNmplQjB0eHFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGtBbDJzaHB2YlE1ZkpPbTdsUjF5M2ZD
      aTBBekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTg1dEhyN3BzQzhYV2hyRXBERGFGQyt6WjhQ
      Q254QjJ1V1kwbTR4SkcKcXZnQ0lIZlJGMWNnYlFjOXVhWUZ2ZFk5UCt6WUUwbFRqVUxNOS9Xbnpv
      aDlZUG14Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVZmV2QXJVUWMrMVUraDhhSFNQc2tvYkFDdnBnd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EVXdNekF3V2hjTk1q
      UXdNVEUyTURVd09EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFMWdNOEZQT0VLSFBiTGhuYmdFSlpIUW82L2ww
      ODJBamwKVU04UTM3dHVPcG9MZ0pSRlgvYjBmd2g0dGV1MHY0UFV0VVNubDZsVmFldWlacVJuNnhN
      bkFxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTQ1hNbXZvdkQyCk5PQk9vdXF0WE1ZUUYrbE9EakFmQmdOVkhTTUVHREFXZ0JU
      a0FsMnNocHZiUTVmSk9tN2xSMXkzZkNpMEF6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05XSmpZMkkyTjJSakxYQTBOelk1TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUtzOGJIajhtS3U5anBjTVgyMWYrUlZmcDVBVytJbXRJbGNnZXFGV2VWVFhBaUFo
      WGVDaXdLYWFEL2ZUCjcxV25qTGVTdEc3Tk05M3R6V1hVeG00VkJMM0pPQT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVhPZzNtRm1oUVZQNSsyaElRVm9GZ01Za3krSXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01URTJNRFExT0RFMFdoY05NalV4
      TVRBMU1EUTFPREUwV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSHY4US9jRXh4R295WlRXTWloNGoxbE9Hd3pWM1JFVVpySzgxRXZieE40SkJvbVAx
      aXgzCkFnU2RDV2p1WTArbThnY055SFByVWhUYnhlYzZqZUIwdHhxalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRrQWwyc2hwdmJR
      NWZKT203bFIxeTNmQ2kwQXpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE4NXRIcjdwc0M4WFdo
      ckVwRERhRkMrelo4UENueEIydVdZMG00eEpHCnF2Z0NJSGZSRjFjZ2JRYzl1YVlGdmRZOVArellF
      MGxUalVMTTkvV256b2g5WVBteAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0
      cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlu
      cxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdB
      d0lCQWdJVWZ4TzZCZi9kaUdxNlgxc3RyTGdsVGVQeEVla3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpNd01URTJNRFV3TXpBd1doY05NalF3TVRFMk1EVXdPREF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVFDL3hoeWRsdUpLNHlPMlkyUGwrZmlTMFkzClZMdDc1MEpjejExcGtL
      dDM1WWVwdkNrMU9TYlNpYStxckxUeFhuZGJGTnZnWkxLK0FFMVpISlNGcG96RW80SUIKTWpDQ0FT
      NHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNBSUJCejF3ZjZNck80Nk1q
      c1VCRWtBaTB4CmhEQWZCZ05WSFNNRUdEQVdnQlRrQWwyc2hwdmJRNWZKT203bFIxeTNmQ2kwQXpC
      QkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdW
      eVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhS
      MGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VR
      aU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNK
      a1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCaDQ4VzV4aFN1QWk4awpoM2MwSU1i
      dmsxNERJd2E1VjBoclZNamlITkxTM2dJZ2RzOE9zMUNHQlNtNXZSV1psNEE3ejRpVHRXY2NaK3F2
      Clk3VnJkUEdHUTFFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVWZ4TzZCZi9kaUdxNlgxc3RyTGdsVGVQ
      eEVla3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJz
      d0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01URTJNRFV3TXpB
      d1doY05NalF3TVRFMk1EVXdPREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhN
      U05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZ
      RFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFDL3hoeWRsdUpLNHlP
      MlkyUGwrZmlTMFkzClZMdDc1MEpjejExcGtLdDM1WWVwdkNrMU9TYlNpYStxckxUeFhuZGJGTnZn
      WkxLK0FFMVpISlNGcG96RW80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVk
      SlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBH
      QTFVZERnUVdCQlNBSUJCejF3ZjZNck80Nk1qc1VCRWtBaTB4CmhEQWZCZ05WSFNNRUdEQVdnQlRr
      QWwyc2hwdmJRNWZKT203bFIxeTNmQ2kwQXpCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVq
      YjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlP
      aUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBi
      aTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhB
      REJFQWlCaDQ4VzV4aFN1QWk4awpoM2MwSU1idmsxNERJd2E1VjBoclZNamlITkxTM2dJZ2RzOE9z
      MUNHQlNtNXZSV1psNEE3ejRpVHRXY2NaK3F2Clk3VnJkUEdHUTFFPQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgK
      EICAgDEYgIBAGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoG
      QWRtaW5zEr8vCgtDb25zb3J0aXVtcxKvLxLkLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsouEq4W
      CgpjYXJyaWVyTVNQEp8WGrsUCgNNU1ASsxQSqBQSpRQKCmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVJQzY1SDl5ZFRBUWZSOG9ZZGFK
      Tm5QUytuUUV3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBeE1UWXdOVEF3TXps
      YUZ3MHlOVEV4TURVd05UQXdNemxhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFSSy9aTlFGeXNWWThTUlRFOENBeG9qbndVUkVLU243dXlXenpNNHRoZjJXL3Fr
      N2htaU15eitFOHNnZDg5VApoVnFPMUNpS3A3ald6SWgzQzJjbmk5ditvMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUY5Ym1MYVNz
      a3ZIWUxUUGc4VFhBUXhzZUdLUXdDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnREVzZEFTZE1xWTll
      VWV0N1ZsTmJDMVhBWThnaHRCdXJyWTE5NEFHSTNwY0NJQ0pud2RqbgorWHIxelFEYWxxMitaUzc3
      aUpUVTZQR3NmRktCWjJFVmZ1RFoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNnQXdJQkFnSVVNc2hRNjI4ZnFpNHo5RGdJ
      cUNqTUZCc2VNWWd3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5
      YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBeE1UWXdOVEEy
      TURCYUZ3MHlOREF4TVRZd05URXhNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFI
      RXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1C
      Z05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRh
      VzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUXJw
      RytsVVBQT0JZUjFWNUNJeG0zKwpYYzdGZU55TVFkSmxjMTBXeEVOYk1YUmdKeXd2aVRyT1U3dDhY
      eEgyekxVNDhsY0VJMXI3MnMraHhjcE5CbndqCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURB
      Z2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRk1LNVJnTlpVVndTaW9qTFZ2OTlV
      dENHNzZTOU1COEdBMVVkSXdRWU1CYUFGQmZXNWkya3JKTHgyQzB6NFBFMQp3RU1iSGhpa01DUUdB
      MVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFUxWm1aak9UWmtORFl0WTJKNFlqZ3dnWTBHCkNDb0RC
      QVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFX
      NGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJX
      NXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElq
      b2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUloQU1qbVpoMWFONUlmb0xma0pR
      TDZYQzdMdjlRZmp5YTVSZjRKcXozYUU2b24KQWlCVHc5TWY2am1FN3ZVemNRMVNGQ3dDLzJYeWlz
      UmRabzQyVHRNUWRoL0c4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNI
      QTI1NkrlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVUlD
      NjVIOXlkVEFRZlI4b1lkYUpOblBTK25RRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncw
      eQpNekF4TVRZd05UQXdNemxhRncweU5URXhNRFV3TlRBd016bGFNRm94Q3pBSkJnTlZCQVlUQWtk
      Q01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFV
      RUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJLL1pOUUZ5c1ZZOFNSVEU4Q0F4b2pud1VSRUtT
      bjd1eVd6ek00dGhmMlcvcWs3aG1pTXl6K0U4c2dkODlUCmhWcU8xQ2lLcDdqV3pJaDNDMmNuaTl2
      K28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdO
      VkhRNEVGZ1FVRjlibUxhU3NrdkhZTFRQZzhUWEFReHNlR0tRd0NnWUlLb1pJemowRQpBd0lEUndB
      d1JBSWdERXNkQVNkTXFZOWVVZXQ3VmxOYkMxWEFZOGdodEJ1cnJZMTk0QUdJM3BjQ0lDSm53ZGpu
      CitYcjF6UURhbHEyK1pTNzdpSlRVNlBHc2ZGS0JaMkVWZnVEWgotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tChoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVy
      TVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBAB
      GgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQ
      GgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFk
      bWlucyoGQWRtaW5zErsXCg9tYW51ZmFjdHVyZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoPbWFu
      dWZhY3R1cmVyTVNQEoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3
      SUJBZ0lVYUdVUWhCZG1DdkRWNWtjdGlUanZYMmlIWVFZd0NnWUlLb1pJemowRUF3SXcKWkRFTE1B
      a0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdO
      bwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5W
      bVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdNVEUyTURRMU9USTJXaGNOTWpVeE1UQTFNRFExT1RJ
      MldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFR
      SERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3
      VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdF
      SEEwSUFCR25EUWFHLzRsSjNla2c0TGViRTkzRENSTXhJTm1JSzVONTAKQUkzelVzay9vYU10dllq
      bkE2ZjFHYThkWFZ0aUNBb204L0hlYjR3L3YwdEE3aWNoV1dDalFqQkFNQThHQTFVZApFd0VCL3dR
      Rk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRSTjlNMnE4eExNRmVE
      CllhY3BIQlpXVWhDT0tqQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFwOTd5U3hBaG9VM0FsOTZW
      V0lXN3JDenIKTjdnZWsxbUNxZGN3OGhUc1RId0NJUUR2encwSlJPZDlFSUR1Q281YkRDb2k0MFds
      aUJ4NVpzVW10RWRPck1uMApRdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQXJXZ0F3SUJBZ0lVQXpRSjNKRlhlNlBwRUoy
      dVg1czNpVmRKM0ZNd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdO
      VkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1
      MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhj
      Tk1qTXdNVEUyTURVd05UQXdXaGNOTWpRd01URTJNRFV4TURBd1dqQ0JoakVMTUFrR0ExVUUKQmhN
      Q1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hO
      WVc1MQpabUZqZEhWeVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1po
      WTNSMWNtVnlNUjh3CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3
      RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFQzRqak1WOFg1T3Rrd2Fnc3pIdHUybk1i
      Y0RMK09KRkFOenNROFNvaGlETlVMUTFQRDVrdApnMWN4bFdML1pxTkNURHk3dGhJcGpEeFJXMVh4
      bVp3Ujk2T0NBU0F3Z2dFY01BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFB
      TUIwR0ExVWREZ1FXQkJUTld3SG9helFmYis1MXo0OXl1eTJTbEZETkVUQWYKQmdOVkhTTUVHREFX
      Z0JUUk45TTJxOHhMTUZlRFlhY3BIQlpXVWhDT0tqQWlCZ05WSFJFRUd6QVpnaGRqWVMxMApiMjlz
      Y3kxbU56ZGpaamMwT0MxNGJtNXdiVENCbHdZSUtnTUVCUVlIQ0FFRWdZcDdJbUYwZEhKeklqcDdJ
      bUZpCllXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvWmk1QlptWnBi
      R2xoZEdsdmJpSTYKSW0xaGJuVm1ZV04wZFhKbGNpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJ
      a0ZrYldsdVFHMWhiblZtWVdOMApkWEpsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlm
      WDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloCkFQOWhkdTU4RnhIZFdTbFdKQVo0cW5jUExWYWdh
      RDdoamgvOGZTV2RPMDlYQWlBQWxnZ0dwTGxCOEg3dlVuSXQKMy8xWHN2L3dUa0pFY2ppaFY1T2U5
      QkZ6aHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVhR1VRaEJkbUN2RFY1
      a2N0aVRqdlgyaUhZUVl3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpNd01URTJNRFExT1RJMldoY05NalV4TVRBMU1EUTFPVEkyV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHbkRRYUcvNGxKM2Vr
      ZzRMZWJFOTNEQ1JNeElObUlLNU41MApBSTN6VXNrL29hTXR2WWpuQTZmMUdhOGRYVnRpQ0FvbTgv
      SGViNHcvdjB0QTdpY2hXV0NqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFJOOU0ycTh4TE1GZUQKWWFjcEhCWldVaENPS2pBS0Jn
      Z3Foa2pPUFFRREFnTkpBREJHQWlFQXA5N3lTeEFob1UzQWw5NlZXSVc3ckN6cgpON2dlazFtQ3Fk
      Y3c4aFRzVEh3Q0lRRHZ6dzBKUk9kOUVJRHVDbzViRENvaTQwV2xpQng1WnNVbXRFZE9yTW4wClF3
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMI
      ARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIj
      CAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0S
      IwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8S
      JQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAK
      FUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0Rh
      dGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMS
      OhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdv
      cml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
