apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.204.81.154:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIJLjVSxOhdyx3vMLyyDnetSnINDpFifpRWXFezPUPZ2uEpZeCpNeCpBeCngKWggBEAEaBgiA
      rO6dBiIKc3lzY2hhbm5lbCpAZGM1OGEzMzc2YjBkZjUzN2FlNjgxODk5YjRkYzczNmExODAxNjFk
      MjBiYWM0Nzc1ZThkZDRjZDMxYmI5ZjE4YhIaEhjNK0i86fTFxEzkQMuBvKDTIcKjkkI3XjISk10K
      kF0SjV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVSWx2b0JEcGx2b1VheFdpdEZxbEJGcG0vNUJJd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRBNU1EUXdORE14V2hjTk1qVXhNREk1TURRd05ETXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJCSHdT
      cXFJS3Z6ODhDcU9HTGV6RzZ6UVg2TUkvNG5neERYS290eEVXeGg3SnJoK3ZWemQKMWhVZmNZbVkx
      OFpRWEkwVlZsb0hXV0U0dlJTd1A2bUVpR0NqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVDN0ZGpyKzRUbTQ4MkZ1TG5vUzJwdjRh
      amNVVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCRi91UmVCWjAwc2ZGRDVySDczc0cvakQ3OFQz
      dnVXSGVSTmFVRmJ2S1UKdndJZ05ja3VjUTVwcU93b0NmWTVzOFhBcWl5VHl3cmpPUGk2eGZRVEhs
      OUVVN2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVVUtoeTh1amNVdFlkOFQzb0Q4dVFwWG9qNHlvd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRBNU1EUXhNREF3V2hjTk1q
      UXdNVEE1TURReE5UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUnEyWm92RGQxSzVBQkJydER2R1lXM29EVkUv
      cXl4Ym8KWnZ1RnFZRXp5NkRvcStLRFBndWx1MEozN2lNNUJ0WmYwTWhFR0k5M0VhbHpSS04vTC9v
      bnFxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTcVI2dks0UHhiCmxQUlMyRVhQRlpJOHY4eEp3REFmQmdOVkhTTUVHREFXZ0JU
      M3RkanIrNFRtNDgyRnVMbm9TMnB2NGFqY1VUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05XSmpZMkkyTjJSakxUVnVlSEI2TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU1TMzZEbWhMcEUyZnE3cWltWjRQOGpVZU9Qa0k5RWVqZ00wSHZPcDVNOVdBaUF3
      TXZoaXYwOWxWSlQwCjJST2YzMjhIZDVwZmpCQ1JyRnFFbzdMQ2QxQTIrZz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlCL3pDQ0FhYWdBd0lCQWdJVUlsdm9CRHBsdm9VYXhXaXRGcWxCRnBtLzVCSXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01UQTVNRFF3TkRNeFdoY05NalV4
      TURJNU1EUXdORE14V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQkh3U3FxSUt2ejg4Q3FPR0xlekc2elFYNk1JLzRuZ3hEWEtvdHhFV3hoN0pyaCt2
      VnpkCjFoVWZjWW1ZMThaUVhJMFZWbG9IV1dFNHZSU3dQNm1FaUdDalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlQzdGRqcis0VG00
      ODJGdUxub1MycHY0YWpjVVRBSwpCZ2dxaGtqT1BRUURBZ05IQURCRUFpQkYvdVJlQlowMHNmRkQ1
      ckg3M3NHL2pENzhUM3Z1V0hlUk5hVUZidktVCnZ3SWdOY2t1Y1E1cHFPd29DZlk1czhYQXFpeVR5
      d3JqT1BpNnhmUVRIbDlFVTdjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4
      ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVWV5RU5pRXB3VE1vNS9r
      QVlOVHFOVHpxd0xiMHdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01U
      QTVNRFF4TVRBd1doY05NalF3TVRBNU1EUXhOakF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhC
      d2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVI5Y0xZ
      SlhBZTZWM0dIVFpvVm9JRWdsQ1BBCmFmMlBVUWN6SjYzWTNVUHNkT1RNVzYxcFFzakx6cVJnUE4x
      VlpOc0ZFenBIV3pES0hTVjcrNGFGR3NKZW80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdP
      b01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4
      RUFqQUFNQjBHQTFVZERnUVdCQlJwV1pqWGhZTkZLYjdFYTVNTXZPZWkzUzZwCkFUQWZCZ05WSFNN
      RUdEQVdnQlQzdGRqcis0VG00ODJGdUxub1MycHY0YWpjVVRCQkJnTlZIUkVFT2pBNGdoaHYKY21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJu
      Y21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hw
      WVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pP
      UFFRREFnTkhBREJFQWlBVlhuak5SaGJVYzY4awp1TzE3c1NmK0RxcjFTczhFeCt0bFRSbFh6ZmNH
      cUFJZ1JPdFNRdzJtSElqWnBUb0xaYmg0aThDTkZ6QWlsZSs4CkZmRDZUbmdZdmJJPQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRD
      Q0FxdWdBd0lCQWdJVWV5RU5pRXB3VE1vNS9rQVlOVHFOVHpxd0xiMHdDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01UQTVNRFF4TVRBd1doY05NalF3TVRBNU1EUXhOakF3
      V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1
      Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3
      SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVI5Y0xZSlhBZTZWM0dIVFpvVm9JRWdsQ1BBCmFmMlBVUWN6
      SjYzWTNVUHNkT1RNVzYxcFFzakx6cVJnUE4xVlpOc0ZFenBIV3pES0hTVjcrNGFGR3NKZW80SUIK
      TWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJC
      Z2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJwV1pqWGhZTkZL
      YjdFYTVNTXZPZWkzUzZwCkFUQWZCZ05WSFNNRUdEQVdnQlQzdGRqcis0VG00ODJGdUxub1MycHY0
      YWpjVVRCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NI
      Rzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZ
      SHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRa
      VzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJ
      am9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBVlhuak5SaGJVYzY4awp1
      TzE3c1NmK0RxcjFTczhFeCt0bFRSbFh6ZmNHcUFJZ1JPdFNRdzJtSElqWnBUb0xaYmg0aThDTkZ6
      QWlsZSs4CkZmRDZUbmdZdmJJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAK
      GAEgBSiAgIAKGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoH
      V3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlu
      cxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoG
      QWRtaW5zEq0vCgtDb25zb3J0aXVtcxKdLxLSLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtErguEq0X
      Cg9tYW51ZmFjdHVyZXJNU1ASmRcaoRUKA01TUBKZFRKOFRKLFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNDekNDQWJLZ0F3SUJBZ0lVVlFhUHI3OGh0
      dG4vQTJ4ZUUvTjVxUXVqY2s4d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qTXdNVEE1TURRd05UUXpXaGNOTWpVeE1ESTVNRFF3TlRReldqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR2lHZm1VTUFX
      Q3lPWDJLbjBNTDMxZTNhZ21WQUhyblhWM2QKSi9LT2drRktGREVJWDA0dGRRT0lYa0JzTHVUcW5j
      MVVpRytFeU1DMngwRWNLYXl1ZW4yalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJ3N1UrckZRKzQ4WnVLCmFxNE9LQTMrRVoyR2tE
      QUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQWZ1VEtsT3dvOUZ4QUxOYlpSbW9DT0g3Nk0KZDlvZHBo
      dHFUSmc3Q2ZqQmFBSWdmKzZrTXovTWF6RHJkUlF1dkdqbEZEYnhLdjVpMzlhSEJJNmdscnF1Zk1v
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERGpDQ0FyV2dBd0lCQWdJVUo5ZitsVXpodG11blNVejdxRVMyanRneHBsUXdDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TVRBNU1EUXhNakF3V2hj
      Tk1qUXdNVEE1TURReE56QXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRTRpVVRlV3lKYkJueTE1OUlBYlZZSE5PSTZJTStQdmpoaWd1Qm5uc1hhd1U0
      aUhtUFVwMlQKSkljNjQ2dStJcUFkTGRscG16TkhwT3lpQjNjRi9BcjVHcU9DQVNBd2dnRWNNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUjMwVWxZ
      RzI2NjE5S0RWd0U0SjBkWU15NE9hREFmCkJnTlZIU01FR0RBV2dCUnc3VStyRlErNDhadUthcTRP
      S0EzK0VaMkdrREFpQmdOVkhSRUVHekFaZ2hkallTMTAKYjI5c2N5MW1OemRqWmpjME9DMDJjMmhy
      WnpDQmx3WUlLZ01FQlFZSENBRUVnWXA3SW1GMGRISnpJanA3SW1GaQpZV011YVc1cGRDSTZJblJ5
      ZFdVaUxDSmhaRzFwYmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2CkltMWhiblZt
      WVdOMGRYSmxjaUlzSW1obUxrVnVjbTlzYkcxbGJuUkpSQ0k2SWtGa2JXbHVRRzFoYm5WbVlXTjAK
      ZFhKbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURS
      d0F3UkFJZwpCYkliU3BzcTVyRmplVjhVZ25OdCszZy9FTXZzOGUrWlRVQVNsQ09ORnFFQ0lIak8w
      K0srTko0Y0crdzcyVER0CnhnaDZkQ1hvSnNaUjdZaHpwMXNJMm9iQQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0N6Q0NBYktnQXdJQkFnSVVWUWFQcjc4aHR0bi9BMnhlRS9ONXFRdWpjazh3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd01UQTVNRFF3TlRReldoY05N
      alV4TURJNU1EUXdOVFF6V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJHaUdmbVVNQVdDeU9YMktuME1MMzFlM2FnbVZBSHJuWFYzZApK
      L0tPZ2tGS0ZERUlYMDR0ZFFPSVhrQnNMdVRxbmMxVWlHK0V5TUMyeDBFY0theXVlbjJqUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      Unc3VStyRlErNDhadUsKYXE0T0tBMytFWjJHa0RBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBZnVU
      S2xPd285RnhBTE5iWlJtb0NPSDc2TQpkOW9kcGh0cVRKZzdDZmpCYUFJZ2YrNmtNei9NYXpEcmRS
      UXV2R2psRkRieEt2NWkzOWFIQkk2Z2xycXVmTW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0
      dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxKqFgoKY2Fycmllck1TUBKbFhq3FAoDTVNQEq8UEqQU
      EqEUCgpjYXJyaWVyTVNQEuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2
      Z0F3SUJBZ0lVYjJGZmJTUmkyMExxWHh2bmZmZjZDRHhjSzNvd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck16QXhNRGt3TkRBMk5UVmFGdzB5TlRFd01qa3dOREEyTlRWYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUVhaYXdSeGkzQUEvcVM4M04z
      Zzd5dngvT0tPdndsdy9CZHFrbTZsb09HUnQ2UlVqbU1ENkZ1Z2k3REJHV28KQXZDcnp6RVJHRHU1
      YVc4WFRUa0NtU2FwbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVmazdSc3JtMXBoNEo4SGNuWEwwS2VlYURQRVF3Q2dZSUtvWkl6
      ajBFCkF3SURSd0F3UkFJZ1kydHpJVFZBN1VLZHV6L3VxcnB6eEdOK21iTUdsVkttNitBZDRvUWFv
      dUVDSUgyWUZKRysKckZvZXJ0TXdPNW1vZk1kYk82ZUVablBuaUJscUVzTVRZT0dLCi0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VEND
      QXBTZ0F3SUJBZ0lVVTVFcFY2dFVSTENZTGF4SVpBUkNFeGhOaEs4d0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck16QXhNRGt3TkRFME1EQmFGdzB5TkRBeE1Ea3dOREU1TURCYU1IZ3hD
      ekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhF
      REFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZ
      MkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFwU0NUejhiN29tc0J1NVNiU2NIUGQKZGNnNHg2eEc0
      VWRpclZsVnRqcEYvZHhxelRNbVlvdW1nWUY1ZzY5S3puOGxkbnpVeEtoUUc2Q1RhTmx0dkZSTwpv
      NElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZS
      ME9CQllFCkZOUXRoalo4L1hDU2NQclFpYldOeUtGQXFNdnNNQjhHQTFVZEl3UVlNQmFBRkg1TzBi
      SzV0YVllQ2ZCM0oxeTkKQ25ubWd6eEVNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRVMVpt
      WmpPVFprTkRZdFkzUm9Zbk13Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlKaFlt
      RmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlY
      UnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1QVky
      RnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJemowRUF3
      SURSd0F3UkFJZ0U5RVk3ZHR5UXJmbjd1bHczVGVNOUpWcUNzRzJ6QUtqQzNEdXRSQW4xZ1VDCklI
      ZktTK05jRUhkU1l2RGM5U2ExWGFvekFWWTdJdUJ4VVFhdVRwUVBlNTF3Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlCOXpDQ0FaNmdBd0lCQWdJVWIyRmZiU1JpMjBMcVh4dm5mZmY2Q0R4Y0szb3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekF4TURrd05EQTJOVFZhRncweU5URXdNamt3TkRB
      Mk5UVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdO
      VkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJF
      dVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFYWmF3
      UnhpM0FBL3FTODNOM2c3eXZ4L09LT3Z3bHcvQmRxa202bG9PR1J0NlJVam1NRDZGdWdpN0RCR1dv
      CkF2Q3J6ekVSR0R1NWFXOFhUVGtDbVNhcG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRH
      QTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVZms3UnNybTFwaDRKOEhjblhMMEtlZWFE
      UEVRd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdZMnR6SVRWQTdVS2R1ei91cXJwenhHTittYk1H
      bFZLbTYrQWQ0b1Fhb3VFQ0lIMllGSkcrCnJGb2VydE13TzVtb2ZNZGJPNmVFWm5QbmlCbHFFc01U
      WU9HSwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAES
      GhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggS
      BggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARIC
      CAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBv
      bGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJl
      EhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBw
      bHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVz
      EhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
