apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.204.81.154:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIHszac0JUv0FpuekW4Cx1i/8YpCLRoaaO7ETO7LhRM8OEqxeCqleCqZeCngKWggBEAEaBgiK
      rv6dBiIKc3lzY2hhbm5lbCpANmZlMDU1ODZmZjUyMWZmNmVjMGZiYzUxYjM5NGRjMjkzN2Q4NDE2
      ZTJhMmYzNGE4ZDUxN2M4NTNkNGFiZDNmZRIaEhhq5mokV4ggQH/GkOgDaSZeOFSCzBjyW7wSqV0K
      pl0So10Svy8KC0NvbnNvcnRpdW1zEq8vEuQuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Syi4StxcK
      D21hbnVmYWN0dXJlck1TUBKjFxqrFQoDTVNQEqMVEpgVEpUVCg9tYW51ZmFjdHVyZXJNU1AShgYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVJRjh0N2ZuV3Vj
      NlRzcFl2TWVRTFJ0SmVvN3d3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpNd01URXlNRFV3TVRVeFdoY05NalV4TVRBeE1EVXdNVFV4V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKZ04yT096VFF0
      UEtUR3kyUFpFUDlDMjZvaHloRUFRemM4QQpmRXliYXpJUmpjQWFKcDZyMW5vSUxLVS9VVlQ3a0Fq
      emxoaUs2dklndzBUUHhJTjVwbTZqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHc1SFlYSWdGL2xXYnIKeFdBSlorRkZZSHBRb3pB
      S0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXJRbWZGRDlnYWFrL0hWQVhrUTBMOUY5RAp3a09jUzVG
      VXgvTmhmNGFVb084Q0lRQ3VpQnR2N2gyQ214TncyTU81bzk0dmI5R2UvR2VFK2s3UjVNS2lldHhn
      CmF3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi3wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJRERqQ0NBcldnQXdJQkFnSVVjRUFHMHBmTlNCR2l0VnlSSndZVUdwS0lqQ2t3Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd01URXlNRFV3TnpB
      d1doY05NalF3TVRFeU1EVXhNakF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJ
      eEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZ
      RFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSQp6ajBEQVFjRFFnQUV6WXVTRDFrQXpwY3RSTVd3aTllRkpJV3VoUW01Z1lCVVJNaU9rZHhU
      ZERXUm1Ia0FyalZMCis3SmQ4R0Z1Um1STnNidmpCYmJqdHZzY2Y5bFlBVjZMZ3FPQ0FTQXdnZ0Vj
      TUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJx
      a3FLV1gxeVBwdlJZSk5nTnlOM0pMUjFZYXpBZgpCZ05WSFNNRUdEQVdnQlR3NUhZWElnRi9sV2Jy
      eFdBSlorRkZZSHBRb3pBaUJnTlZIUkVFR3pBWmdoZGpZUzEwCmIyOXNjeTFtTnpkalpqYzBPQzFx
      WmpKb1pEQ0Jsd1lJS2dNRUJRWUhDQUVFZ1lwN0ltRjBkSEp6SWpwN0ltRmkKWVdNdWFXNXBkQ0k2
      SW5SeWRXVWlMQ0poWkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNgpJbTFo
      Ym5WbVlXTjBkWEpsY2lJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUcxaGJuVm1Z
      V04wCmRYSmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVB
      d0lEUndBd1JBSWcKTkxRUEJ6M2dZNE5HNStDN2gvcXVsL1VrOXc1NVZZNU9TNzNrNXFkRkRTY0NJ
      RXJYelY1cVlQcG9kQlp2a2MyRgo0RWxoY24yaWM5eW5ESGN0ZDlVcVhYckMKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lVSUY4dDdmbld1YzZUc3BZdk1lUUxSdEplbzd3d0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdNVEV5TURVd01UVXhX
      aGNOTWpVeE1UQXhNRFV3TVRVeFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSmdOMk9PelRRdFBLVEd5MlBaRVA5QzI2b2h5aEVBUXpj
      OEEKZkV5YmF6SVJqY0FhSnA2cjFub0lMS1UvVVZUN2tBanpsaGlLNnZJZ3cwVFB4SU41cG02alFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlR3NUhZWElnRi9sV2JyCnhXQUpaK0ZGWUhwUW96QUtCZ2dxaGtqT1BRUURBZ05KQURCR0Fp
      RUFyUW1mRkQ5Z2Fhay9IVkFYa1EwTDlGOUQKd2tPY1M1RlV4L05oZjRhVW9POENJUUN1aUJ0djdo
      MkNteE53Mk1PNW85NHZiOUdlL0dlRStrN1I1TUtpZXR4Zwphdz09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51
      ZmFjdHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMS
      EQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoD
      TVNQErcUEqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUIrRENDQVo2Z0F3SUJBZ0lVRGUxQ0tZSzhSczNEVW9Bc3AvL2xXQytBS2FNd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck16QXhNVEl3TlRBeU5UbGFGdzB5TlRFeE1ERXdOVEF5TlRs
      YU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFj
      TUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJG
      eWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU2IyWUNmbC9T
      YWs0RlJwbkZ5bUNVcDJ5bHR6b1dwSHNKWkU3N3ltNWZ5cGl2NHI3V3kxK3NJUHF5aU1mZmcKVk0x
      dGFtRUthcDh0Y204dWtGMkNLV0ZTbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVk
      RHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVWNzloamFqbFJ3eVJ6Sk5xTndNMktESWZxd293
      Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFOdUZHMXRYOHlQWTJGbFRZQjFVeFcwRW4rOU5BVTBt
      WGQvUzJHYmtsYllHQWlBN2I1Y20KY0FHZGloUGlhazJMajNodWwwcjkyRmFMekxOK1l0REtHQ0dU
      dFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDN1RDQ0FwU2dBd0lCQWdJVVNTM0E0VlFMaVJsK3RLdmduYnF0YTE1Smhlc3dDZ1lJ
      S29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFE
      REE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekF4TVRJd05UQTRNREJhRncweU5EQXhNVEl3
      TlRFek1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4
      TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1
      TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRend1bG0xUHFuR0xLSWhlTWdt
      M25SCk5CS0ZlUWs5UHhweHI5anI4TWZoTTRTTFNCM3NMRzNmL1ZEUUhVN2Nsc29WbXR0WG45YU04
      YzZGd3NpUm1uT0UKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIv
      d1FDTUFBd0hRWURWUjBPQkJZRQpGTnRvUlRsSHcxRXJwMFpBMmt5dU43VW40TUVVTUI4R0ExVWRJ
      d1FZTUJhQUZGZS9ZWTJvNVVjTWtjeVRhamNECk5pZ3lINnNLTUNRR0ExVWRFUVFkTUJ1Q0dXTmhM
      WFJ2YjJ4ekxUVTFabVpqT1Raa05EWXRiakpzYzJZd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5Smhk
      SFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lh
      R1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJ
      am9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0Nn
      WUkKS29aSXpqMEVBd0lEUndBd1JBSWdQY2JjRlE2NEFlZDNTTGxBN0UrL0laNnVZaFNuMEVyd1Fv
      ckNXbER6aHM0QwpJQklCdGMraWxQZWllSGRjcmFIeTFkL1dCaU82MFloRlhTN29BTnNaWWtNMwot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVEZTFDS1lLOFJzM0RVb0FzcC8vbFdD
      K0FLYU13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1S
      Y3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBeE1USXdOVEF5TlRsYUZ3
      MHlOVEV4TURFd05UQXlOVGxhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIy
      NWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1C
      VUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkMKQUFTYjJZQ2ZsL1NhazRGUnBuRnltQ1VwMnlsdHpvV3BIc0paRTc3eW01ZnlwaXY0cjdX
      eTErc0lQcXlpTWZmZwpWTTF0YW1FS2FwOHRjbTh1a0YyQ0tXRlNvMEl3UURBUEJnTlZIUk1CQWY4
      RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVY3OWhqYWpsUnd5
      UnpKTnFOd00yS0RJZnF3b3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU51RkcxdFg4eVBZMkZs
      VFlCMVV4VzBFbis5TkFVMG1YZC9TMkdia2xiWUdBaUE3YjVjbQpjQUdkaWhQaWFrMkxqM2h1bDBy
      OTJGYUx6TE4rWXRES0dDR1R0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMi
      MwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZB
      ZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRv
      cnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFk
      ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoV
      Q2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zEpsrCgdPcmRlcmVy
      Eo8rEtIWCg5zdXBwbHljaGFpbk1TUBK/FhrLFAoDTVNQEsMUErgUErUUCg5zdXBwbHljaGFpbk1T
      UBL1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVUtIQjdP
      eUhtUlk0UFFkQVdpMzlhaEJ2MldETXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpI
      aGNOTWpNd01URXlNRFV3TURNNVdoY05NalV4TVRBeE1EVXdNRE01V2pCZU1Rc3dDUVlEVlFRR0V3
      SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0Jn
      TlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGRE
      QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCQkhSMmErcVZONUE1KzJKL1BlZEFo
      Q2pvSW9wd2UxS1lUbCsvVC9JdGZLaHNaN1dyNCtSCnY0YUhsNlJyQUxIbHFTUzBIdS9vYjE2UGhm
      bVQ3VG9admJPalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlRUcjd5QmYrY0IwaFQ1OTFhTENRcE1KNFpTQnpBSwpCZ2dxaGtqT1BR
      UURBZ05KQURCR0FpRUFuelJBeGNJd3VKcEltdWQ5ZENGa1NZQUJQUkNwc01CVTBXVGVBKzZRCnFE
      d0NJUUQrR21WTlltRVcwc1dPZ1BBbWJ3dFRkc3VRU2Y3YThNQlB4VFpsSE9USGFnPT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRU
      Q0NBb2lnQXdJQkFnSVVRS3dURERnMEVVYUc2NEZCSHAvZFB6TzVaVkF3Q2dZSUtvWkl6ajBFQXdJ
      dwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhC
      d2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qTXdNVEV5TURVd05UQXdXaGNOTWpRd01URXlNRFV4TURB
      d1dqQnNNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5
      dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3
      R0ExVUVBd3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUV1c2I2YmlXVVh6emh6OUs1TnNzak04aU1rZWdlblpkZApXR256emdi
      LzlTMEJ3dnpTWmFHWjUwUVA3RWczZjRKSE1DSnBnVHFLZFRDRkNLeVAvOE1kT2FPQ0FSUXdnZ0VR
      Ck1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlM5
      WUMzRnhNTU8KRmJhMWNkWEFqbHFBQlR4NVZqQWZCZ05WSFNNRUdEQVdnQlRUcjd5QmYrY0IwaFQ1
      OTFhTENRcE1KNFpTQnpBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzTldKalkySTJOMlJq
      TFdKamJISTJNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFp
      T2lKMGNuVmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlp
      TENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFp
      TENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3ClJBSWdJSEln
      aEV5M1gvSGVPMDBkaFBhUlJQMnpMSFhVNE4rWEJzUzYrYnZNUFRzQ0lDN0lzQ2JWelNxaXp4cGUK
      aGlRRkEvV2RreCtpLy95ZmVUc1RzL3VMeUxYbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIO
      CgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FUQ0NBYWFn
      QXdJQkFnSVVLSEI3T3lIbVJZNFBRZEFXaTM5YWhCdjJXRE13Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qTXdNVEV5TURVd01ETTVXaGNOTWpVeE1UQXhNRFV3TURNNVdqQmVN
      UXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1i
      MjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNl
      V05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkJIUjJhK3FW
      TjVBNSsySi9QZWRBaENqb0lvcHdlMUtZVGwrL1QvSXRmS2hzWjdXcjQrUgp2NGFIbDZSckFMSGxx
      U1MwSHUvb2IxNlBoZm1UN1RvWnZiT2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURW
      UjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUVHI3eUJmK2NCMGhUNTkxYUxDUXBNSjRaU0J6
      QUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBbnpSQXhjSXd1SnBJbXVkOWRDRmtTWUFCUFJDcHNN
      QlUwV1RlQSs2UQpxRHdDSVFEK0dtVk5ZbUVXMHNXT2dQQW1id3RUZHN1UVNmN2E4TUJQeFRabEhP
      VEhhZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVhZGVycxIsEiII
      ARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3JpdGVycxIsEiII
      ARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgB
      EiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50
      EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGh8K
      E0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFf
      NF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9y
      ZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlEQkRDQ0FxdWdBd0lCQWdJVVNtRjB1Tm1hZDdkeTF0UGdEQmdmcmhnbk1rc3dDZ1lJS29aSXpq
      MEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallT
      NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01URXlNRFV3TlRBd1doY05NalF3TVRFeU1E
      VXhNREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1U
      TXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNt
      VnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJn
      Y3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRYRmdLUnk2YTJCRWNnK2poM2p5VXUwdkdKCjdT
      L0QvbzBsTEJFY3hKZGV5S2YrSGJGajljUmRBcDgrMXIzdzA1ZFFvQUxlaHU0WklOTis0RFhEMllT
      SG80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFV
      RkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJlV0V1
      MG0yOTAyYm9zaXZNVWxzeTBVbVJnCm56QWZCZ05WSFNNRUdEQVdnQlRUcjd5QmYrY0IwaFQ1OTFh
      TENRcE1KNFpTQnpCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZ
      SENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5K
      dmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1
      VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBM1hBWVNwdlNw
      RXU0Swp5amkrSHNRYzF4QnoydmZtNHM0OGtDRWFvWm8wSFFJZ0ZKS0t1Z3JsUnpHQ05XWFg1ZWVN
      bllhZEorNThMRVFUCkZMdmsrZE5UM1Y4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVVNtRjB1Tm1hZDdk
      eTF0UGdEQmdmcmhnbk1rc3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpN
      d01URXlNRFV3TlRBd1doY05NalF3TVRFeU1EVXhNREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakVi
      Ck1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJs
      Y21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6
      ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRY
      RmdLUnk2YTJCRWNnK2poM2p5VXUwdkdKCjdTL0QvbzBsTEJFY3hKZGV5S2YrSGJGajljUmRBcDgr
      MXIzdzA1ZFFvQUxlaHU0WklOTis0RFhEMllTSG80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFE
      QWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1C
      QWY4RUFqQUFNQjBHQTFVZERnUVdCQlJlV0V1MG0yOTAyYm9zaXZNVWxzeTBVbVJnCm56QWZCZ05W
      SFNNRUdEQVdnQlRUcjd5QmYrY0IwaFQ1OTFhTENRcE1KNFpTQnpCQkJnTlZIUkVFT2pBNGdoaHYK
      Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVk
      WEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1h
      V3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpk
      WEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Fo
      a2pPUFFRREFnTkhBREJFQWlBM1hBWVNwdlNwRXU0Swp5amkrSHNRYzF4QnoydmZtNHM0OGtDRWFv
      Wm8wSFFJZ0ZKS0t1Z3JsUnpHQ05XWFg1ZWVNbllhZEorNThMRVFUCkZMdmsrZE5UM1Y4PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0
      Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFk
      bWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRp
      b24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoG
      QWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaJgoQSGFz
      aGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1
      Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIx
      LnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmls
      aXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxAC
      GgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
